#==========================================================
#= Articoli Web Service - Versione Base
#==========================================================
server:
  port: 5051
  
spring:
  application:
    name: ArticoliWebService
#==========================================================
#= PARAMETRI DBMS POSTGRESQL 
#==========================================================
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: sandonadipiave2022
    url: jdbc:postgresql://192.168.1.6:5433/AlphaShop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

